version: '3.9'

services:
  db:
    image: postgres:15
    container_name: challenger-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: challenger-backend
    restart: unless-stopped
    env_file:
      - src/backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app/src/backend
    working_dir: /app/src
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    build:
      context: .
      dockerfile: src/bot/Dockerfile
    container_name: challenger-bot
    restart: unless-stopped   # меняем на перезапуск при остановке
    env_file:
      - src/bot/.env
    depends_on:
      - backend
    volumes:
      - ./src/bot:/app/src/bot   # монтируем весь src для отслеживания изменений
    working_dir: /app/src

volumes:
  postgres_data:
